apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource-quota-manager.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "resource-quota-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "resource-quota-manager.selectorLabels" . | nindent 4 }}
