apiVersion: v1
data:
  config.yaml: |
    issuer: https://kubeflow.ubilink.ai/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true

    connectors:
    # Authentik connector（原有，保留）
    - type: oidc
      id: authentik
      name: Authentik
      config:
        issuer: https://authentik.ubilink.ai/application/o/kubeflow-dex/
        clientID: hxl26gPgWU1qQQmKzFWVroYZePKcbw4auph3w05Z
        clientSecret: 9gRbUNVcX95HFSFsfuxqzCMI07pSzCKVQDci4LOThVdTElwdd1WC6asaC9BcWkiUZFaLr7afU9M2MM1ADdmfboE8NoBTV60SIswCXx4IhNGZiF04jufU57nw8EBvgUyM
        redirectURI: https://kubeflow.ubilink.ai/dex/callback
        insecureSkipEmailVerified: true
        insecureEnableGroups: true
        insecureSkipVerify: true
        scopes:
        - openid
        - profile
        - email
        - groups

    staticClients:
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/oauth2/callback"]
      name: "Dex Login Application"
      secretEnv: OIDC_CLIENT_SECRET
      public: false
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"issuer: https://kubeflow.ubilink.ai/dex\nstorage:\n  type: kubernetes\n  config:\n    inCluster: true\nweb:\n  http: 0.0.0.0:5556\nlogger:\n  level: \"debug\"\n  format: text\noauth2:\n  skipApprovalScreen: true\n\nconnectors:\n# Authentik connector（原有，保留）\n- type: oidc\n  id: authentik\n  name: Authentik\n  config:\n    issuer: https://authentik.ubilink.ai/application/o/kubeflow-dex/\n    clientID: hxl26gPgWU1qQQmKzFWVroYZePKcbw4auph3w05Z\n    clientSecret: 9gRbUNVcX95HFSFsfuxqzCMI07pSzCKVQDci4LOThVdTElwdd1WC6asaC9BcWkiUZFaLr7afU9M2MM1ADdmfboE8NoBTV60SIswCXx4IhNGZiF04jufU57nw8EBvgUyM\n    redirectURI: https://kubeflow.ubilink.ai/dex/callback\n    insecureSkipEmailVerified: true\n    insecureEnableGroups: true\n    insecureSkipVerify: true\n    scopes:\n    - openid\n    - profile\n    - email\n    - groups\n\nstaticClients:\n- idEnv: OIDC_CLIENT_ID\n  redirectURIs: [\"/oauth2/callback\"]\n  name: \"Dex Login Application\"\n  secretEnv: OIDC_CLIENT_SECRET\n  public: false\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-10-02T08:53:47Z","name":"dex","namespace":"auth","resourceVersion":"134499056","uid":"1354d6c7-6900-4fcf-9781-822468c6ce3b"}}
  creationTimestamp: "2025-10-02T08:53:47Z"
  name: dex
  namespace: auth
  resourceVersion: "135365145"
  uid: 1354d6c7-6900-4fcf-9781-822468c6ce3b
