apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kubeflow
  labels:
    app: kserve
    app.kubernetes.io/name: kserve
data:
  ingress: |
    {
      "enableGatewayApi": false,
      "kserveIngressGateway": "kserve/kserve-ingress-gateway",
      "ingressGateway": "kubeflow/kubeflow-gateway",
      "localGateway": "knative-serving/knative-local-gateway",
      "localGatewayService": "knative-local-gateway.istio-system.svc.cluster.local",
      "ingressDomain": "api.ubilink.ai",
      "ingressClassName": "istio",
      "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
      "urlScheme": "http",
      "disableIstioVirtualHost": false,
      "disableIngressCreation": false,
      "pathTemplate": "/serving/{{ .Namespace }}/{{ .Name }}"
    }
  storageInitializer: |
    {
      "image": "kserve/storage-initializer:v0.15.2",
      "memoryRequest": "100Mi",
      "memoryLimit": "1Gi",
      "cpuRequest": "100m",
      "cpuLimit": "1",
      "gpuRequest": "0",
      "gpuLimit": "0"
    }
  logger: |
    {
      "image": "kserve/agent:v0.15.2",
      "memoryRequest": "100Mi",
      "memoryLimit": "1Gi",
      "cpuRequest": "100m",
      "cpuLimit": "1",
      "defaultUrl": "http://default-broker"
    }
  batcher: |
    {
      "image": "kserve/agent:v0.15.2",
      "memoryRequest": "100Mi",
      "memoryLimit": "1Gi",
      "cpuRequest": "100m",
      "cpuLimit": "1"
    }
  agent: |
    {
      "image": "kserve/agent:v0.15.2",
      "memoryRequest": "100Mi",
      "memoryLimit": "1Gi",
      "cpuRequest": "100m",
      "cpuLimit": "1"
    }
  router: |
    {
      "image": "kserve/router:v0.15.2",
      "memoryRequest": "100Mi",
      "memoryLimit": "1Gi",
      "cpuRequest": "100m",
      "cpuLimit": "1"
    }
  metricsAggregator: |
    {
      "enableMetricAggregation": "false",
      "enablePrometheusScraping": "true"
    }
